on:
    push:
        branches: [prod-latest]
name: Resume Github Automated Deploy
jobs:
    web-deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2.3.2
            
            - name: 🔨 Build Project
                run:|
                    npm install
                    npm run build
            
            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.0.0
              with:
                  server: 66.186.19.254
                  port: 21
                  username: github-deploy
                  password: ${{secrets.smartaspftp}}
                  local-dir: ./dist/
                  server-dir: ./
