on:
    push:
        branches:
            - prod-latest
name: Resume Github Automated Deploy
jobs:
    web-deploy:
        name: Deploy
        runs-on: prod-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2.3.2
            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.0.0
              with:
                  server: ftp.site4now.net
                  username: filipecavalcante-001
                  password: Rzr7qX6dnjuWeNL
                  local-dir: ./dist/
                  server-dir: ./resume/resume/
